'use client'

import React, { useState } from 'react'
import EditItem from '@/components/EditItem'

const metadata = {
  title: 'Edit',
  description: 'Generated by create next app',
}

const getItemById = async (id) => {
  try {
    const res = await fetch(`http://127.0.0.1:3000/api/items/${id}`, {
      cache: "no-cache",
    })

    if (!res.ok) {
      throw new Error('Failed to fetch the item.')
    }

    return res.json()
  } catch (error) {
    console.log(error)
  }
}

export default async function Edit({ params }) {
  
  const { id } = params
  const { item } = await getItemById(id)
  const { title, description } = item 
  
  

  return (
    <EditItem id={id} title={title} description={description} />
  )
}
